joint_impedance_controller:
  ros__parameters:
    arm_id: "fr3"
    csv_path: "/home/anthony-ho/trajectory_validation.csv"
    log_path: "/home/anthony-ho/franka_ros2_ws/src/nonlinear_deepc_controller/data_processing/tau_log_train.csv"
    robot_state_topic: "/franka_robot_state_broadcaster/robot_state"
    log_decimation: 1
    stop_logging_at_end: true
    post_log_window: 0.0
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5